---
# - name: test export
#   shell: |
#       # export mizo=mutaz
#       echo helloooo
#       echo $TYPEORM_CONNECTION
#       echo $TYPEORM_HOST
#   register: result

# - debug:
#     msg: '{{ result }}'


# - name: "upgrade packages."
#   become: true
#   apt:
# #     upgrade: "yes"

- name: "download NodeJS"
  become: true 
  shell: |
    curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install --global n
    sudo n 13.8.0 

- name: "install NodeJS"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present  