---
- name: Extract artifact
  unarchive:
    src:  artifact.tar.gz
    dest: /opt/artifact
- name: start app
  shell: |
    cd /opt/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start