---
- name: Create a directory for artifact
  ansible.builtin.file:
    path: /tmp/artifact
    state: directory

- name: Extract artifact
  unarchive:
    src:  artifact.tar.gz
    dest: /tmp/artifact
- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    netstat -tupln
  args:
    chdir: /tmp/artifact/
  register: result
- debug:
    msg: '{{ result }}'

- name: start app
  shell: |
    echo $TYPEORM_CONNECTION >> /tmp/envi.txt
    echo $TYPEORM_ENTITIES >> /tmp/envi.txt
    echo $TYPEORM_HOST >> /tmp/envi.txt
    echo $TYPEORM_PORT >> /tmp/envi.txt
    echo $TYPEORM_USERNAME >> /tmp/envi.txt
    echo $TYPEORM_PASSWORD >> /tmp/envi.txt
    echo $TYPEORM_DATABASE >> /tmp/envi.txt
    echo $TYPEORM_MIGRATIONS >> /tmp/envi.txt
    echo $TYPEORM_MIGRATIONS_DIR >> /tmp/envi.txt
   

  


