---
- name: Extract artifact
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /opt/artifact
- name: start app
  shell: |
    cd /opt/artifact
    npm install
    pm2 stop default
    pm2 start npm -- start