---

- name: Create a directory for artifact
  file:
    path: ~/app
    state: directory

- name: Extract artifact
  unarchive:
    src:  artifact.tar.gz
    dest: ~/app

- name: installing dep
  shell: |
    export NODE_ENV=production
    export VERSION=1

    export TYPEORM_MIGRATIONS_DIR=./migrations
    export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_MIGRATIONS=./migrations/*{.ts,.js}
    export TYPEORM_HOST=udapeople.cfsfhcxwx9rs.us-east-1.rds.amazonaws.com

    cd ~/app
    sudo npm install typescript@latest -g 
    npm install




- name: start app
  shell: |
    cd ~/app/dist
    
    sudo npm install typescript@latest -g
    npm i
    
    pm2 stop default
    pm2 start main.js
    # netstat -tupln
    # npm run start
  # args:
  #   chdir: /tmp/artifact/
  register: result
- debug:
    msg: '{{ result }}'



- name: start app
  shell: |
    echo $TYPEORM_CONNECTION >> /tmp/envi.txt
    echo $TYPEORM_ENTITIES >> /tmp/envi.txt
    echo $TYPEORM_HOST >> /tmp/envi.txt
    echo $TYPEORM_PORT >> /tmp/envi.txt
    echo $TYPEORM_USERNAME >> /tmp/envi.txt
    echo $TYPEORM_PASSWORD >> /tmp/envi.txt
    echo $TYPEORM_DATABASE >> /tmp/envi.txt
    echo $TYPEORM_MIGRATIONS >> /tmp/envi.txt
    echo $TYPEORM_MIGRATIONS_DIR >> /tmp/envi.txt

