---
- name: Create a directory for artifact
  ansible.builtin.file:
    path: /tmp/artifact
    state: directory

- name: Extract artifact
  unarchive:
    src:  artifact.tar.gz
    dest: /tmp/artifact
- name: start app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    netstat -tupln
  args:
    chdir: /tmp/artifact/
  register: result
- debug:
    msg: '{{ result }}'
