---
- name: Create a directory for artifact
  file:
    path: ~/app
    state: directory

- name: Extract artifact
  unarchive:
    src:  artifact.tar.gz
    dest: ~/app

- name: installing dep
  shell: |
    cd ~/app
    npm install



- name: start app
  shell: |
    cd ~/app/dist
    
    pm2 stop default
    pm2 start main.js
    # netstat -tupln
    # npm run start
  # args:
  #   chdir: /tmp/artifact/
  register: result
- debug:
    msg: '{{ result }}'



# - name: start app
#   shell: |
#     echo $TYPEORM_CONNECTION >> /tmp/envi.txt
#     echo $TYPEORM_ENTITIES >> /tmp/envi.txt
#     echo $TYPEORM_HOST >> /tmp/envi.txt
#     echo $TYPEORM_PORT >> /tmp/envi.txt
#     echo $TYPEORM_USERNAME >> /tmp/envi.txt
#     echo $TYPEORM_PASSWORD >> /tmp/envi.txt
#     echo $TYPEORM_DATABASE >> /tmp/envi.txt
#     echo $TYPEORM_MIGRATIONS >> /tmp/envi.txt
#     echo $TYPEORM_MIGRATIONS_DIR >> /tmp/envi.txt

