FROM nginx:latest
RUN apt-get update && \
    apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x |  bash - &&  apt install -y nodejs && npm install --global n && n 13.8.0 

COPY package*.json ./
RUN npm install 

COPY . .
RUN npm run build 
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 8300
CMD ["nginx", "-g", "daemon off;"]

