FROM node:13.8.0-alpine3.11
# FROM ubuntu:latest
# RUN apt update && \
#     apt install -y curl
# RUN curl -fsSL https://deb.nodesource.com/setup_lts.x |  bash - &&  apt install -y nodejs && npm install --global n && n 13.8.0 
COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build 
ENV TYPEORM_HOST=host.docker.internal \
 TYPEORM_PORT=5432 \
 TYPEORM_USERNAME=postgres \
 TYPEORM_PASSWORD=mysecretpassword \
 TYPEORM_DATABASE=postgres \
 NODE_ENV=production \
 VERSION=1 \
 TYPEORM_CONNECTION=postgres \
 TYPEORM_MIGRATIONS_DIR=./src/migrations \
 TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts \
 TYPEORM_MIGRATIONS=./src/migrations/*.ts

# RUN npm run migrations


# RUN npm install && npm install typescript@latest -g && npm install @types/express-unless --save-dev

EXPOSE 3030

CMD ["npm","run","start"]