pipeline {
 agent none
  environment {
     
        KUBECONFIG = credentials('kubernetescred')
    }
  
  stages {
    stage('checkout & build backend') {
            
            agent {
            //     kubernetes {
            //     inheritFrom 'kube-2'
            //     defaultContainer 'alpine'

            // }
            label 'jenkins'
            }
            steps {
       
        
          sh '''
                pwd
                    '''
   }
  }
    //  stage('building docker image') {

    //   agent {
    //             node {
    //             label 'jenkins'
                
    //         }
    //         }
           
    //   steps {         
              
    //     script {
    //     dockerImage = docker.build("ahmedeldesoki/udabackend:${BUILD_NUMBER}", "./backend")
    //     withDockerRegistry([ credentialsId: "docker-hub", url: "" ]) {
    //                 dockerImage.push()
    //   }
    //   }      
    //   }     
    // }
    
  }
}