pipeline {
  environment {
     
        KUBECONFIG = credentials('kubernetescred')
    }
  agent {
    node {
      label 'jenkins'
     
   }
  }
  stages {
    stage('checkout & build backend') {
            steps {
       
        //   git branch: 'jenkins', url: 'https://github.com/ahmed-eldesoki/udapeople.git'
     
          sh '''
                pwd
                    '''
   }
  }
     stage('building docker image') {
           
      steps {         
              
        script {
     dockerImage = docker.build("ahmedeldesoki/udabackend:${BUILD_NUMBER}", "./backend")
      withDockerRegistry([ credentialsId: "docker-hub", url: "" ]) {
                 dockerImage.push()
      }
      }      
      }     
    }
    
  }
}