pipeline {
 options {
        skipDefaultCheckout(true)
    }


  agent none 
  stages {

    stage('building docker image') {

        agent {
                node {
                    label 'jenkins'
                    
                }
            }
            
        steps {         
            copyArtifacts(projectName: 'deploying-in-k8s')

             // Extract the tar file
            
             sh '''
                   tar -xzf *.tar.gz 
                   ls -lh
                   '''
            script {
            dockerImage = docker.build("ahmedeldesoki/udabackend:${BUILD_NUMBER}", "./")
            withDockerRegistry([ credentialsId: "docker-hub", url: "" ]) {
                        dockerImage.push()
           }
          }      
         }     
        }
    stage('Deploying Backend') {
            environment {

            KUBECONFIG = credentials('kubernetescred')
        }
        agent {
            kubernetes {
            inheritFrom 'kube-2'
            defaultContainer 'alpine'

        }
        
        }
        steps {

           git url: "https://github.com/ahmed-eldesoki/udapeople.git", branch: 'jenkins'
        
            sh '''
                
                helm install udapeople-0 helm/udapeople

                '''
    }
    }
    
  }
}