apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uda-app-foo
  namespace: argocd
spec:
  destination:
    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: argocd/app-foo
    repoURL: https://github.com/ahmed-eldesoki/udapeople.git
    targetRevision: jenkins
  syncPolicy:
    automated: {}

    # syncOptions:
    # - ApplyOutOfSyncOnly=true